---
#	Playbook: launchInstance.yaml
#	Author: Donald Raikes
#	Date: 03/18/2022
#
#	Launch a new compute instance and install necessary software on it.

- name: Launch and configure a new compute instance
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    # common networking definitions
    quad_zero_route: "0.0.0.0/0"
    TCP_protocol: "6"
    SSH_port: "22"

    config_profile_name: "{{ lookup('env','SAMPLE_CONFIG_PROFILE_NAME') }}"
    vcn_name: "{{ lookup('env', 'VCN_ID') }}"
    vcn_cidr_block: "{{ lookup('env','VCN_CIDR') }}"

    instance_subnet_id: "{{ lookup('env','SUBNET_OCID') }}"
    subnet_cidr: "{{ lookup('env','SUBNET_CIDR') }}"
    subnet_name: "{{ lookup('env','SUBNET_NAME') }}"


    instance_shape: "{{ lookup('env', 'SHAPE') }}"
    instance_hostname: "{{ lookup('env','DISPLAYNAME') }}"

    #########################################
    # Tenancy specific configuration
    # *Note* - Override the following variables based on your tenancy
    # or set a valid value for the corresponding environment variable
    #########################################
    instance_ad: "{{ lookup('env', 'AVAILABILITY_DOMAIN') }}"
    instance_fault_domain: "{{ lookup('env','FAULT_DOMAIN') }}"
    instance_compartment: "{{ lookup('env', 'COMPARTMENT_ID') }}"
    # provide an "OL" image
    # find OL image ocids per region here: https://docs.cloud.oracle.com/iaas/images/image/501c6e22-4dc6-4e99-b045-cae47aae343f/
    instance_image: "{{ lookup('env', 'IMAGE') }}"

  tasks:
    - block:
      - import_tasks: setup.yml

      - set_fact:
          SSH_AUTHORIZED_KEYS: "{{ lookup('env', 'SAMPLE_PUBLIC_SSH_KEY') if 'SAMPLE_PUBLIC_SSH_KEY' in ansible_env else lookup('file',  my_test_public_key ) }}"

      - import_tasks: createInstance.yml
      - import_tasks: installSoftware.yml
      - import_tasks: teardown.yml


      rescue:

        - import_tasks: teardown.yml
