- name: List all compute instances in this region and compartment
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    compartment_id: "{{ lookup('env','COMPARTMENT_OCID') }}"
  tasks:
    - name: Gather instance facts
      oci_compute_instance_facts:
        compartment_id: "{{ compartment_id }}"
      register: results

    - name: Print the results
      debug:
        msg: "{{ results }}"
